/*
 * This file is generated by jOOQ.
 */
package io.kida.model;


import io.kida.model.tables.DataAssociation;
import io.kida.model.tables.DataPrescription;
import io.kida.model.tables.DataVarietyEnterprice;
import io.kida.model.tables.SysAbnormalLog;
import io.kida.model.tables.SysOperRecord;
import io.kida.model.tables.SysUser;
import io.kida.model.tables.SysUserBuried;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>tools</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATA_ASSOCIATION_DA_DRUG_NAME = Indexes0.DATA_ASSOCIATION_DA_DRUG_NAME;
    public static final Index DATA_PRESCRIPTION_DP_DRUG_NAME = Indexes0.DATA_PRESCRIPTION_DP_DRUG_NAME;
    public static final Index DATA_PRESCRIPTION_DP_VARIETY = Indexes0.DATA_PRESCRIPTION_DP_VARIETY;
    public static final Index DATA_VARIETY_ENTERPRICE_DVE_VARIETY = Indexes0.DATA_VARIETY_ENTERPRICE_DVE_VARIETY;
    public static final Index SYS_ABNORMAL_LOG_IDX_SAL_OPER_DATE = Indexes0.SYS_ABNORMAL_LOG_IDX_SAL_OPER_DATE;
    public static final Index SYS_ABNORMAL_LOG_IDX_SAL_REQUESTIP = Indexes0.SYS_ABNORMAL_LOG_IDX_SAL_REQUESTIP;
    public static final Index SYS_ABNORMAL_LOG_IDX_SAL_USERNAME = Indexes0.SYS_ABNORMAL_LOG_IDX_SAL_USERNAME;
    public static final Index SYS_OPER_RECORD_IDX_SOR_DATE = Indexes0.SYS_OPER_RECORD_IDX_SOR_DATE;
    public static final Index SYS_OPER_RECORD_IDX_SOR_USER = Indexes0.SYS_OPER_RECORD_IDX_SOR_USER;
    public static final Index SYS_USER_IDX_STATUS = Indexes0.SYS_USER_IDX_STATUS;
    public static final Index SYS_USER_BURIED_IDX_IP_URI = Indexes0.SYS_USER_BURIED_IDX_IP_URI;
    public static final Index SYS_USER_BURIED_IDX_OPER_TYPE = Indexes0.SYS_USER_BURIED_IDX_OPER_TYPE;
    public static final Index SYS_USER_BURIED_IDX_SSXT_DATE = Indexes0.SYS_USER_BURIED_IDX_SSXT_DATE;
    public static final Index SYS_USER_BURIED_IDX_SSXT_URI = Indexes0.SYS_USER_BURIED_IDX_SSXT_URI;
    public static final Index SYS_USER_BURIED_IDX_TYPE = Indexes0.SYS_USER_BURIED_IDX_TYPE;
    public static final Index SYS_USER_BURIED_IDX_USERID = Indexes0.SYS_USER_BURIED_IDX_USERID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATA_ASSOCIATION_DA_DRUG_NAME = Internal.createIndex("DA_DRUG_NAME", DataAssociation.DATA_ASSOCIATION, new OrderField[] { DataAssociation.DATA_ASSOCIATION.DRUG_NAME }, false);
        public static Index DATA_PRESCRIPTION_DP_DRUG_NAME = Internal.createIndex("DP_DRUG_NAME", DataPrescription.DATA_PRESCRIPTION, new OrderField[] { DataPrescription.DATA_PRESCRIPTION.DRUG_NAME }, false);
        public static Index DATA_PRESCRIPTION_DP_VARIETY = Internal.createIndex("DP_VARIETY", DataPrescription.DATA_PRESCRIPTION, new OrderField[] { DataPrescription.DATA_PRESCRIPTION.VARIETY }, false);
        public static Index DATA_VARIETY_ENTERPRICE_DVE_VARIETY = Internal.createIndex("DVE_VARIETY", DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE, new OrderField[] { DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.VARIETY }, false);
        public static Index SYS_ABNORMAL_LOG_IDX_SAL_OPER_DATE = Internal.createIndex("IDX_SAL_OPER_DATE", SysAbnormalLog.SYS_ABNORMAL_LOG, new OrderField[] { SysAbnormalLog.SYS_ABNORMAL_LOG.OPER_DATE }, false);
        public static Index SYS_ABNORMAL_LOG_IDX_SAL_REQUESTIP = Internal.createIndex("IDX_SAL_REQUESTIP", SysAbnormalLog.SYS_ABNORMAL_LOG, new OrderField[] { SysAbnormalLog.SYS_ABNORMAL_LOG.REQUESTIP }, false);
        public static Index SYS_ABNORMAL_LOG_IDX_SAL_USERNAME = Internal.createIndex("IDX_SAL_USERNAME", SysAbnormalLog.SYS_ABNORMAL_LOG, new OrderField[] { SysAbnormalLog.SYS_ABNORMAL_LOG.USERNAME }, false);
        public static Index SYS_OPER_RECORD_IDX_SOR_DATE = Internal.createIndex("IDX_SOR_DATE", SysOperRecord.SYS_OPER_RECORD, new OrderField[] { SysOperRecord.SYS_OPER_RECORD.OPER_TIME }, false);
        public static Index SYS_OPER_RECORD_IDX_SOR_USER = Internal.createIndex("IDX_SOR_USER", SysOperRecord.SYS_OPER_RECORD, new OrderField[] { SysOperRecord.SYS_OPER_RECORD.USER_ID }, false);
        public static Index SYS_USER_IDX_STATUS = Internal.createIndex("IDX_STATUS", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.STATUS }, false);
        public static Index SYS_USER_BURIED_IDX_IP_URI = Internal.createIndex("IDX_IP_URI", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.IP, SysUserBuried.SYS_USER_BURIED.SSXT }, false);
        public static Index SYS_USER_BURIED_IDX_OPER_TYPE = Internal.createIndex("IDX_OPER_TYPE", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.OPER_TYPE, SysUserBuried.SYS_USER_BURIED.SSXT }, false);
        public static Index SYS_USER_BURIED_IDX_SSXT_DATE = Internal.createIndex("IDX_SSXT_DATE", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.ACCESS_DATE, SysUserBuried.SYS_USER_BURIED.SSXT }, false);
        public static Index SYS_USER_BURIED_IDX_SSXT_URI = Internal.createIndex("IDX_SSXT_URI", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.URI, SysUserBuried.SYS_USER_BURIED.SSXT }, false);
        public static Index SYS_USER_BURIED_IDX_TYPE = Internal.createIndex("IDX_TYPE", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.TYPE, SysUserBuried.SYS_USER_BURIED.SSXT }, false);
        public static Index SYS_USER_BURIED_IDX_USERID = Internal.createIndex("IDX_USERID", SysUserBuried.SYS_USER_BURIED, new OrderField[] { SysUserBuried.SYS_USER_BURIED.SYS_CODE, SysUserBuried.SYS_USER_BURIED.UID }, false);
    }
}
