/*
 * This file is generated by jOOQ.
 */
package io.kida.model;


import io.kida.model.tables.CmmItembank;
import io.kida.model.tables.DataAssociation;
import io.kida.model.tables.DataPrescription;
import io.kida.model.tables.DataVarietyEnterprice;
import io.kida.model.tables.Md5Change;
import io.kida.model.tables.SysAbnormalLog;
import io.kida.model.tables.SysDataDict;
import io.kida.model.tables.SysOperRecord;
import io.kida.model.tables.SysPermission;
import io.kida.model.tables.SysPermissionConfig;
import io.kida.model.tables.SysRole;
import io.kida.model.tables.SysRolePermission;
import io.kida.model.tables.SysUser;
import io.kida.model.tables.SysUserBuried;
import io.kida.model.tables.SysUserRole;
import io.kida.model.tables.records.CmmItembankRecord;
import io.kida.model.tables.records.DataAssociationRecord;
import io.kida.model.tables.records.DataPrescriptionRecord;
import io.kida.model.tables.records.DataVarietyEnterpriceRecord;
import io.kida.model.tables.records.Md5ChangeRecord;
import io.kida.model.tables.records.SysAbnormalLogRecord;
import io.kida.model.tables.records.SysDataDictRecord;
import io.kida.model.tables.records.SysOperRecordRecord;
import io.kida.model.tables.records.SysPermissionConfigRecord;
import io.kida.model.tables.records.SysPermissionRecord;
import io.kida.model.tables.records.SysRolePermissionRecord;
import io.kida.model.tables.records.SysRoleRecord;
import io.kida.model.tables.records.SysUserBuriedRecord;
import io.kida.model.tables.records.SysUserRecord;
import io.kida.model.tables.records.SysUserRoleRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>tools</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CmmItembankRecord, Long> IDENTITY_CMM_ITEMBANK = Identities0.IDENTITY_CMM_ITEMBANK;
    public static final Identity<Md5ChangeRecord, Long> IDENTITY_MD5_CHANGE = Identities0.IDENTITY_MD5_CHANGE;
    public static final Identity<SysAbnormalLogRecord, Integer> IDENTITY_SYS_ABNORMAL_LOG = Identities0.IDENTITY_SYS_ABNORMAL_LOG;
    public static final Identity<SysOperRecordRecord, Long> IDENTITY_SYS_OPER_RECORD = Identities0.IDENTITY_SYS_OPER_RECORD;
    public static final Identity<SysPermissionRecord, Long> IDENTITY_SYS_PERMISSION = Identities0.IDENTITY_SYS_PERMISSION;
    public static final Identity<SysPermissionConfigRecord, Long> IDENTITY_SYS_PERMISSION_CONFIG = Identities0.IDENTITY_SYS_PERMISSION_CONFIG;
    public static final Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = Identities0.IDENTITY_SYS_ROLE;
    public static final Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Identities0.IDENTITY_SYS_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CmmItembankRecord> KEY_CMM_ITEMBANK_PRIMARY = UniqueKeys0.KEY_CMM_ITEMBANK_PRIMARY;
    public static final UniqueKey<DataAssociationRecord> KEY_DATA_ASSOCIATION_UNI_KEY = UniqueKeys0.KEY_DATA_ASSOCIATION_UNI_KEY;
    public static final UniqueKey<DataPrescriptionRecord> KEY_DATA_PRESCRIPTION_UNI_DP_KEY = UniqueKeys0.KEY_DATA_PRESCRIPTION_UNI_DP_KEY;
    public static final UniqueKey<DataVarietyEnterpriceRecord> KEY_DATA_VARIETY_ENTERPRICE_UNI_DVE_KEY = UniqueKeys0.KEY_DATA_VARIETY_ENTERPRICE_UNI_DVE_KEY;
    public static final UniqueKey<Md5ChangeRecord> KEY_MD5_CHANGE_PRIMARY = UniqueKeys0.KEY_MD5_CHANGE_PRIMARY;
    public static final UniqueKey<SysAbnormalLogRecord> KEY_SYS_ABNORMAL_LOG_PRIMARY = UniqueKeys0.KEY_SYS_ABNORMAL_LOG_PRIMARY;
    public static final UniqueKey<SysDataDictRecord> KEY_SYS_DATA_DICT_PRIMARY = UniqueKeys0.KEY_SYS_DATA_DICT_PRIMARY;
    public static final UniqueKey<SysOperRecordRecord> KEY_SYS_OPER_RECORD_PRIMARY = UniqueKeys0.KEY_SYS_OPER_RECORD_PRIMARY;
    public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = UniqueKeys0.KEY_SYS_PERMISSION_PRIMARY;
    public static final UniqueKey<SysPermissionConfigRecord> KEY_SYS_PERMISSION_CONFIG_PRIMARY = UniqueKeys0.KEY_SYS_PERMISSION_CONFIG_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_UK_SYS_ROLE_1 = UniqueKeys0.KEY_SYS_ROLE_UK_SYS_ROLE_1;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_UK_SYS_ROLE_2 = UniqueKeys0.KEY_SYS_ROLE_UK_SYS_ROLE_2;
    public static final UniqueKey<SysRolePermissionRecord> KEY_SYS_ROLE_PERMISSION_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PERMISSION_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_UK_SYS_USER_ACCOUNT = UniqueKeys0.KEY_SYS_USER_UK_SYS_USER_ACCOUNT;
    public static final UniqueKey<SysUserBuriedRecord> KEY_SYS_USER_BURIED_PRIMARY = UniqueKeys0.KEY_SYS_USER_BURIED_PRIMARY;
    public static final UniqueKey<SysUserBuriedRecord> KEY_SYS_USER_BURIED_ID_UNIQUE = UniqueKeys0.KEY_SYS_USER_BURIED_ID_UNIQUE;
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CmmItembankRecord, Long> IDENTITY_CMM_ITEMBANK = Internal.createIdentity(CmmItembank.CMM_ITEMBANK, CmmItembank.CMM_ITEMBANK.ID);
        public static Identity<Md5ChangeRecord, Long> IDENTITY_MD5_CHANGE = Internal.createIdentity(Md5Change.MD5_CHANGE, Md5Change.MD5_CHANGE.ID);
        public static Identity<SysAbnormalLogRecord, Integer> IDENTITY_SYS_ABNORMAL_LOG = Internal.createIdentity(SysAbnormalLog.SYS_ABNORMAL_LOG, SysAbnormalLog.SYS_ABNORMAL_LOG.ID);
        public static Identity<SysOperRecordRecord, Long> IDENTITY_SYS_OPER_RECORD = Internal.createIdentity(SysOperRecord.SYS_OPER_RECORD, SysOperRecord.SYS_OPER_RECORD.OPER_ID);
        public static Identity<SysPermissionRecord, Long> IDENTITY_SYS_PERMISSION = Internal.createIdentity(SysPermission.SYS_PERMISSION, SysPermission.SYS_PERMISSION.PERMISSION_ID);
        public static Identity<SysPermissionConfigRecord, Long> IDENTITY_SYS_PERMISSION_CONFIG = Internal.createIdentity(SysPermissionConfig.SYS_PERMISSION_CONFIG, SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_CONFIG_ID);
        public static Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = Internal.createIdentity(SysRole.SYS_ROLE, SysRole.SYS_ROLE.ROLE_ID);
        public static Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Internal.createIdentity(SysUser.SYS_USER, SysUser.SYS_USER.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CmmItembankRecord> KEY_CMM_ITEMBANK_PRIMARY = Internal.createUniqueKey(CmmItembank.CMM_ITEMBANK, "KEY_cmm_itembank_PRIMARY", new TableField[] { CmmItembank.CMM_ITEMBANK.ID }, true);
        public static final UniqueKey<DataAssociationRecord> KEY_DATA_ASSOCIATION_UNI_KEY = Internal.createUniqueKey(DataAssociation.DATA_ASSOCIATION, "KEY_data_association_UNI_KEY", new TableField[] { DataAssociation.DATA_ASSOCIATION.DRUG_NAME, DataAssociation.DATA_ASSOCIATION.APPROVAL_NUMBER, DataAssociation.DATA_ASSOCIATION.PRODUCTION_UNIT, DataAssociation.DATA_ASSOCIATION.PREPARATION, DataAssociation.DATA_ASSOCIATION.SPECIFICATIONS }, true);
        public static final UniqueKey<DataPrescriptionRecord> KEY_DATA_PRESCRIPTION_UNI_DP_KEY = Internal.createUniqueKey(DataPrescription.DATA_PRESCRIPTION, "KEY_data_prescription_UNI_DP_KEY", new TableField[] { DataPrescription.DATA_PRESCRIPTION.DRUG_NAME, DataPrescription.DATA_PRESCRIPTION.VARIETY }, true);
        public static final UniqueKey<DataVarietyEnterpriceRecord> KEY_DATA_VARIETY_ENTERPRICE_UNI_DVE_KEY = Internal.createUniqueKey(DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE, "KEY_data_variety_enterprice_UNI_DVE_KEY", new TableField[] { DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.VARIETY, DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.ENTERPRICE, DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.ENTERPRICE_ROLE }, true);
        public static final UniqueKey<Md5ChangeRecord> KEY_MD5_CHANGE_PRIMARY = Internal.createUniqueKey(Md5Change.MD5_CHANGE, "KEY_md5_change_PRIMARY", new TableField[] { Md5Change.MD5_CHANGE.ID }, true);
        public static final UniqueKey<SysAbnormalLogRecord> KEY_SYS_ABNORMAL_LOG_PRIMARY = Internal.createUniqueKey(SysAbnormalLog.SYS_ABNORMAL_LOG, "KEY_sys_abnormal_log_PRIMARY", new TableField[] { SysAbnormalLog.SYS_ABNORMAL_LOG.ID }, true);
        public static final UniqueKey<SysDataDictRecord> KEY_SYS_DATA_DICT_PRIMARY = Internal.createUniqueKey(SysDataDict.SYS_DATA_DICT, "KEY_sys_data_dict_PRIMARY", new TableField[] { SysDataDict.SYS_DATA_DICT.DID, SysDataDict.SYS_DATA_DICT.PARENT_ID }, true);
        public static final UniqueKey<SysOperRecordRecord> KEY_SYS_OPER_RECORD_PRIMARY = Internal.createUniqueKey(SysOperRecord.SYS_OPER_RECORD, "KEY_sys_oper_record_PRIMARY", new TableField[] { SysOperRecord.SYS_OPER_RECORD.OPER_ID }, true);
        public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = Internal.createUniqueKey(SysPermission.SYS_PERMISSION, "KEY_sys_permission_PRIMARY", new TableField[] { SysPermission.SYS_PERMISSION.PERMISSION_ID }, true);
        public static final UniqueKey<SysPermissionConfigRecord> KEY_SYS_PERMISSION_CONFIG_PRIMARY = Internal.createUniqueKey(SysPermissionConfig.SYS_PERMISSION_CONFIG, "KEY_sys_permission_config_PRIMARY", new TableField[] { SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_CONFIG_ID }, true);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", new TableField[] { SysRole.SYS_ROLE.ROLE_ID }, true);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_UK_SYS_ROLE_1 = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_UK_SYS_ROLE_1", new TableField[] { SysRole.SYS_ROLE.ROLE_CODE }, true);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_UK_SYS_ROLE_2 = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_UK_SYS_ROLE_2", new TableField[] { SysRole.SYS_ROLE.ROLE_NAME }, true);
        public static final UniqueKey<SysRolePermissionRecord> KEY_SYS_ROLE_PERMISSION_PRIMARY = Internal.createUniqueKey(SysRolePermission.SYS_ROLE_PERMISSION, "KEY_sys_role_permission_PRIMARY", new TableField[] { SysRolePermission.SYS_ROLE_PERMISSION.ROLE_ID, SysRolePermission.SYS_ROLE_PERMISSION.PERMISSION_ID }, true);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", new TableField[] { SysUser.SYS_USER.USER_ID }, true);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_UK_SYS_USER_ACCOUNT = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_UK_SYS_USER_ACCOUNT", new TableField[] { SysUser.SYS_USER.USER_ACCOUNT }, true);
        public static final UniqueKey<SysUserBuriedRecord> KEY_SYS_USER_BURIED_PRIMARY = Internal.createUniqueKey(SysUserBuried.SYS_USER_BURIED, "KEY_sys_user_buried_PRIMARY", new TableField[] { SysUserBuried.SYS_USER_BURIED.ID }, true);
        public static final UniqueKey<SysUserBuriedRecord> KEY_SYS_USER_BURIED_ID_UNIQUE = Internal.createUniqueKey(SysUserBuried.SYS_USER_BURIED, "KEY_sys_user_buried_ID_UNIQUE", new TableField[] { SysUserBuried.SYS_USER_BURIED.ID }, true);
        public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "KEY_sys_user_role_PRIMARY", new TableField[] { SysUserRole.SYS_USER_ROLE.USER_ID, SysUserRole.SYS_USER_ROLE.ROLE_ID }, true);
    }
}
