/*
 * This file is generated by jOOQ.
 */
package io.kida.model;


import io.kida.model.tables.CmmItembank;
import io.kida.model.tables.DataAssociation;
import io.kida.model.tables.DataPrescription;
import io.kida.model.tables.DataVarietyEnterprice;
import io.kida.model.tables.Md5Change;
import io.kida.model.tables.SysAbnormalLog;
import io.kida.model.tables.SysDataDict;
import io.kida.model.tables.SysOperRecord;
import io.kida.model.tables.SysPermission;
import io.kida.model.tables.SysPermissionConfig;
import io.kida.model.tables.SysRole;
import io.kida.model.tables.SysRolePermission;
import io.kida.model.tables.SysUser;
import io.kida.model.tables.SysUserBuried;
import io.kida.model.tables.SysUserRole;


/**
 * Convenience access to all tables in tools
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 中医药达人题目爬取
     */
    public static final CmmItembank CMM_ITEMBANK = CmmItembank.CMM_ITEMBANK;

    /**
     * 数据关联
     */
    public static final DataAssociation DATA_ASSOCIATION = DataAssociation.DATA_ASSOCIATION;

    /**
     * 方剂数据
     */
    public static final DataPrescription DATA_PRESCRIPTION = DataPrescription.DATA_PRESCRIPTION;

    /**
     * 品种与企业对应数据
     */
    public static final DataVarietyEnterprice DATA_VARIETY_ENTERPRICE = DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE;

    /**
     * md5转换明文表
     */
    public static final Md5Change MD5_CHANGE = Md5Change.MD5_CHANGE;

    /**
     * 异常日志表
     */
    public static final SysAbnormalLog SYS_ABNORMAL_LOG = SysAbnormalLog.SYS_ABNORMAL_LOG;

    /**
     * 数据字典表
     */
    public static final SysDataDict SYS_DATA_DICT = SysDataDict.SYS_DATA_DICT;

    /**
     * 系统操作记录表
     */
    public static final SysOperRecord SYS_OPER_RECORD = SysOperRecord.SYS_OPER_RECORD;

    /**
     * 权限表
     */
    public static final SysPermission SYS_PERMISSION = SysPermission.SYS_PERMISSION;

    /**
     * 权限配置表
     */
    public static final SysPermissionConfig SYS_PERMISSION_CONFIG = SysPermissionConfig.SYS_PERMISSION_CONFIG;

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 角色权限关联表
     */
    public static final SysRolePermission SYS_ROLE_PERMISSION = SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * 用户信息埋点表
     */
    public static final SysUserBuried SYS_USER_BURIED = SysUserBuried.SYS_USER_BURIED;

    /**
     * 用户角色关联表
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;
}
