/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables;


import io.kida.model.Indexes;
import io.kida.model.Keys;
import io.kida.model.Tools;
import io.kida.model.tables.records.SysUserBuriedRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 用户信息埋点表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserBuried extends TableImpl<SysUserBuriedRecord> {

    private static final long serialVersionUID = 79127482;

    /**
     * The reference instance of <code>tools.sys_user_buried</code>
     */
    public static final SysUserBuried SYS_USER_BURIED = new SysUserBuried();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUserBuriedRecord> getRecordType() {
        return SysUserBuriedRecord.class;
    }

    /**
     * The column <code>tools.sys_user_buried.ID</code>. 主键UUID
     */
    public final TableField<SysUserBuriedRecord, String> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "主键UUID");

    /**
     * The column <code>tools.sys_user_buried.IP</code>. IP地址
     */
    public final TableField<SysUserBuriedRecord, String> IP = createField(DSL.name("IP"), org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "IP地址");

    /**
     * The column <code>tools.sys_user_buried.URI</code>. 访问地址
     */
    public final TableField<SysUserBuriedRecord, String> URI = createField(DSL.name("URI"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "访问地址");

    /**
     * The column <code>tools.sys_user_buried.SYS_CODE</code>. 系统编码（例如：abc）
     */
    public final TableField<SysUserBuriedRecord, String> SYS_CODE = createField(DSL.name("SYS_CODE"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "系统编码（例如：abc）");

    /**
     * The column <code>tools.sys_user_buried.SSXT</code>. 模块（后续用于统计）
     */
    public final TableField<SysUserBuriedRecord, String> SSXT = createField(DSL.name("SSXT"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "模块（后续用于统计）");

    /**
     * The column <code>tools.sys_user_buried.BUZZ_ID</code>. 业务id
     */
    public final TableField<SysUserBuriedRecord, String> BUZZ_ID = createField(DSL.name("BUZZ_ID"), org.jooq.impl.SQLDataType.CLOB, this, "业务id");

    /**
     * The column <code>tools.sys_user_buried.ACCESS_DATE</code>. 访问时间
     */
    public final TableField<SysUserBuriedRecord, String> ACCESS_DATE = createField(DSL.name("ACCESS_DATE"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "访问时间");

    /**
     * The column <code>tools.sys_user_buried.TYPE</code>. 访问端口：pc\wechat\app
     */
    public final TableField<SysUserBuriedRecord, String> TYPE = createField(DSL.name("TYPE"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "访问端口：pc\\wechat\\app");

    /**
     * The column <code>tools.sys_user_buried.DURATION_TIME</code>. 持续时间（ms）
     */
    public final TableField<SysUserBuriedRecord, Long> DURATION_TIME = createField(DSL.name("DURATION_TIME"), org.jooq.impl.SQLDataType.BIGINT, this, "持续时间（ms）");

    /**
     * The column <code>tools.sys_user_buried.OPER_TYPE</code>. 操作类型：view（浏览）、click（操作）
     */
    public final TableField<SysUserBuriedRecord, String> OPER_TYPE = createField(DSL.name("OPER_TYPE"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("view", org.jooq.impl.SQLDataType.VARCHAR)), this, "操作类型：view（浏览）、click（操作）");

    /**
     * The column <code>tools.sys_user_buried.ANALYSIS_LABEL</code>. 分析标签（随意输入，后续用于统计）
     */
    public final TableField<SysUserBuriedRecord, String> ANALYSIS_LABEL = createField(DSL.name("ANALYSIS_LABEL"), org.jooq.impl.SQLDataType.CLOB, this, "分析标签（随意输入，后续用于统计）");

    /**
     * The column <code>tools.sys_user_buried.UID</code>. 用户id
     */
    public final TableField<SysUserBuriedRecord, Long> UID = createField(DSL.name("UID"), org.jooq.impl.SQLDataType.BIGINT, this, "用户id");

    /**
     * Create a <code>tools.sys_user_buried</code> table reference
     */
    public SysUserBuried() {
        this(DSL.name("sys_user_buried"), null);
    }

    /**
     * Create an aliased <code>tools.sys_user_buried</code> table reference
     */
    public SysUserBuried(String alias) {
        this(DSL.name(alias), SYS_USER_BURIED);
    }

    /**
     * Create an aliased <code>tools.sys_user_buried</code> table reference
     */
    public SysUserBuried(Name alias) {
        this(alias, SYS_USER_BURIED);
    }

    private SysUserBuried(Name alias, Table<SysUserBuriedRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysUserBuried(Name alias, Table<SysUserBuriedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户信息埋点表"), TableOptions.table());
    }

    public <O extends Record> SysUserBuried(Table<O> child, ForeignKey<O, SysUserBuriedRecord> key) {
        super(child, key, SYS_USER_BURIED);
    }

    @Override
    public Schema getSchema() {
        return Tools.TOOLS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_USER_BURIED_IDX_IP_URI, Indexes.SYS_USER_BURIED_IDX_OPER_TYPE, Indexes.SYS_USER_BURIED_IDX_SSXT_DATE, Indexes.SYS_USER_BURIED_IDX_SSXT_URI, Indexes.SYS_USER_BURIED_IDX_TYPE, Indexes.SYS_USER_BURIED_IDX_USERID);
    }

    @Override
    public UniqueKey<SysUserBuriedRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USER_BURIED_PRIMARY;
    }

    @Override
    public List<UniqueKey<SysUserBuriedRecord>> getKeys() {
        return Arrays.<UniqueKey<SysUserBuriedRecord>>asList(Keys.KEY_SYS_USER_BURIED_PRIMARY, Keys.KEY_SYS_USER_BURIED_ID_UNIQUE);
    }

    @Override
    public SysUserBuried as(String alias) {
        return new SysUserBuried(DSL.name(alias), this);
    }

    @Override
    public SysUserBuried as(Name alias) {
        return new SysUserBuried(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserBuried rename(String name) {
        return new SysUserBuried(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserBuried rename(Name name) {
        return new SysUserBuried(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, String, String, String, String, String, String, Long, String, String, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
