/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables;


import io.kida.model.Keys;
import io.kida.model.Tools;
import io.kida.model.tables.records.SysUserRoleRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 用户角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRole extends TableImpl<SysUserRoleRecord> {

    private static final long serialVersionUID = -933290707;

    /**
     * The reference instance of <code>tools.sys_user_role</code>
     */
    public static final SysUserRole SYS_USER_ROLE = new SysUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUserRoleRecord> getRecordType() {
        return SysUserRoleRecord.class;
    }

    /**
     * The column <code>tools.sys_user_role.USER_ID</code>. 用户编号
     */
    public final TableField<SysUserRoleRecord, Long> USER_ID = createField(DSL.name("USER_ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "用户编号");

    /**
     * The column <code>tools.sys_user_role.ROLE_ID</code>. 角色编号
     */
    public final TableField<SysUserRoleRecord, Long> ROLE_ID = createField(DSL.name("ROLE_ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "角色编号");

    /**
     * Create a <code>tools.sys_user_role</code> table reference
     */
    public SysUserRole() {
        this(DSL.name("sys_user_role"), null);
    }

    /**
     * Create an aliased <code>tools.sys_user_role</code> table reference
     */
    public SysUserRole(String alias) {
        this(DSL.name(alias), SYS_USER_ROLE);
    }

    /**
     * Create an aliased <code>tools.sys_user_role</code> table reference
     */
    public SysUserRole(Name alias) {
        this(alias, SYS_USER_ROLE);
    }

    private SysUserRole(Name alias, Table<SysUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysUserRole(Name alias, Table<SysUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户角色关联表"), TableOptions.table());
    }

    public <O extends Record> SysUserRole(Table<O> child, ForeignKey<O, SysUserRoleRecord> key) {
        super(child, key, SYS_USER_ROLE);
    }

    @Override
    public Schema getSchema() {
        return Tools.TOOLS;
    }

    @Override
    public UniqueKey<SysUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USER_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<SysUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<SysUserRoleRecord>>asList(Keys.KEY_SYS_USER_ROLE_PRIMARY);
    }

    @Override
    public SysUserRole as(String alias) {
        return new SysUserRole(DSL.name(alias), this);
    }

    @Override
    public SysUserRole as(Name alias) {
        return new SysUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserRole rename(String name) {
        return new SysUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserRole rename(Name name) {
        return new SysUserRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
