/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;
import io.kida.model.tables.CmmItembank;
import io.kida.model.tables.records.CmmItembankRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Configuration;


import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO;
import io.github.jklingsporn.vertx.jooq.completablefuture.jdbc.JDBCCompletableFutureQueryExecutor;
/**
 * 中医药达人题目爬取
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmmItembankDao extends AbstractVertxDAO<CmmItembankRecord, io.kida.model.tables.pojos.CmmItembank, Long, CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>>, CompletableFuture<io.kida.model.tables.pojos.CmmItembank>, CompletableFuture<Integer>, CompletableFuture<Long>> implements io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO<CmmItembankRecord,io.kida.model.tables.pojos.CmmItembank,Long> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public CmmItembankDao(Configuration configuration, io.vertx.core.Vertx vertx) {
        super(CmmItembank.CMM_ITEMBANK, io.kida.model.tables.pojos.CmmItembank.class, new JDBCCompletableFutureQueryExecutor<CmmItembankRecord,io.kida.model.tables.pojos.CmmItembank,Long>(configuration,io.kida.model.tables.pojos.CmmItembank.class,vertx));
    }

    @Override
    protected Long getId(io.kida.model.tables.pojos.CmmItembank object) {
        return object.getId();
    }

    /**
     * Find records that have <code>QUESTION_TITLE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByQuestionTitle(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.QUESTION_TITLE.in(values));
    }

    /**
     * Find records that have <code>OPTION_A IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionA(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_A.in(values));
    }

    /**
     * Find records that have <code>OPTION_B IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionB(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_B.in(values));
    }

    /**
     * Find records that have <code>OPTION_C IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionC(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_C.in(values));
    }

    /**
     * Find records that have <code>OPTION_D IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionD(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_D.in(values));
    }

    /**
     * Find records that have <code>OPTION_E IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionE(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_E.in(values));
    }

    /**
     * Find records that have <code>OPTION_F IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByOptionF(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.OPTION_F.in(values));
    }

    /**
     * Find records that have <code>ADD_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByAddTime(Collection<LocalDateTime> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.ADD_TIME.in(values));
    }

    /**
     * Find records that have <code>ACTICLE_NAME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByActicleName(Collection<String> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.ACTICLE_NAME.in(values));
    }

    /**
     * Find records that have <code>PAGE_NUM IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyByPageNum(Collection<Integer> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.PAGE_NUM.in(values));
    }

    /**
     * Find records that have <code>SUBJECT_NUM IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.CmmItembank>> findManyBySubjectNum(Collection<Integer> values) {
        return findManyByCondition(CmmItembank.CMM_ITEMBANK.SUBJECT_NUM.in(values));
    }

    @Override
    public JDBCCompletableFutureQueryExecutor<CmmItembankRecord,io.kida.model.tables.pojos.CmmItembank,Long> queryExecutor(){
        return (JDBCCompletableFutureQueryExecutor<CmmItembankRecord,io.kida.model.tables.pojos.CmmItembank,Long>) super.queryExecutor();
    }
}
