/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;
import io.kida.model.tables.SysPermissionConfig;
import io.kida.model.tables.records.SysPermissionConfigRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Configuration;


import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO;
import io.github.jklingsporn.vertx.jooq.completablefuture.jdbc.JDBCCompletableFutureQueryExecutor;
/**
 * 权限配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionConfigDao extends AbstractVertxDAO<SysPermissionConfigRecord, io.kida.model.tables.pojos.SysPermissionConfig, Long, CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>>, CompletableFuture<io.kida.model.tables.pojos.SysPermissionConfig>, CompletableFuture<Integer>, CompletableFuture<Long>> implements io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO<SysPermissionConfigRecord,io.kida.model.tables.pojos.SysPermissionConfig,Long> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public SysPermissionConfigDao(Configuration configuration, io.vertx.core.Vertx vertx) {
        super(SysPermissionConfig.SYS_PERMISSION_CONFIG, io.kida.model.tables.pojos.SysPermissionConfig.class, new JDBCCompletableFutureQueryExecutor<SysPermissionConfigRecord,io.kida.model.tables.pojos.SysPermissionConfig,Long>(configuration,io.kida.model.tables.pojos.SysPermissionConfig.class,vertx));
    }

    @Override
    protected Long getId(io.kida.model.tables.pojos.SysPermissionConfig object) {
        return object.getPermissionConfigId();
    }

    /**
     * Find records that have <code>PERMISSION_URL IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByPermissionUrl(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_URL.in(values));
    }

    /**
     * Find records that have <code>PERMISSION_CONFIG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByPermissionConfig(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_CONFIG.in(values));
    }

    /**
     * Find records that have <code>SEQ_NO IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyBySeqNo(Collection<Integer> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.SEQ_NO.in(values));
    }

    /**
     * Find records that have <code>REMARK IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByRemark(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.REMARK.in(values));
    }

    /**
     * Find records that have <code>PERMISSION_NAME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByPermissionName(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_NAME.in(values));
    }

    /**
     * Find records that have <code>ICON IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByIcon(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.ICON.in(values));
    }

    /**
     * Find records that have <code>PERMISSION_TYPE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByPermissionType(Collection<Boolean> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.PERMISSION_TYPE.in(values));
    }

    /**
     * Find records that have <code>P_PERMISSION_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByPPermissionId(Collection<Integer> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.P_PERMISSION_ID.in(values));
    }

    /**
     * Find records that have <code>SYS_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyBySysId(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.SYS_ID.in(values));
    }

    /**
     * Find records that have <code>SORT_NO IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyBySortNo(Collection<Integer> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.SORT_NO.in(values));
    }

    /**
     * Find records that have <code>DISPLAY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByDisplay(Collection<Integer> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.DISPLAY.in(values));
    }

    /**
     * Find records that have <code>ALIVE_FLAG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByAliveFlag(Collection<Integer> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.ALIVE_FLAG.in(values));
    }

    /**
     * Find records that have <code>ADD_USER_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByAddUserId(Collection<Long> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.ADD_USER_ID.in(values));
    }

    /**
     * Find records that have <code>ADD_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByAddTime(Collection<LocalDateTime> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.ADD_TIME.in(values));
    }

    /**
     * Find records that have <code>OPR_USER_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByOprUserId(Collection<Long> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.OPR_USER_ID.in(values));
    }

    /**
     * Find records that have <code>OPR_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByOprTime(Collection<LocalDateTime> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.OPR_TIME.in(values));
    }

    /**
     * Find records that have <code>SUBSYS_CODE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyBySubsysCode(Collection<String> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.SUBSYS_CODE.in(values));
    }

    /**
     * Find records that have <code>CHECK_FLAG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysPermissionConfig>> findManyByCheckFlag(Collection<Byte> values) {
        return findManyByCondition(SysPermissionConfig.SYS_PERMISSION_CONFIG.CHECK_FLAG.in(values));
    }

    @Override
    public JDBCCompletableFutureQueryExecutor<SysPermissionConfigRecord,io.kida.model.tables.pojos.SysPermissionConfig,Long> queryExecutor(){
        return (JDBCCompletableFutureQueryExecutor<SysPermissionConfigRecord,io.kida.model.tables.pojos.SysPermissionConfig,Long>) super.queryExecutor();
    }
}
