/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;
import io.kida.model.tables.SysUserBuried;
import io.kida.model.tables.records.SysUserBuriedRecord;

import java.util.Collection;

import org.jooq.Configuration;


import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO;
import io.github.jklingsporn.vertx.jooq.completablefuture.jdbc.JDBCCompletableFutureQueryExecutor;
/**
 * 用户信息埋点表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserBuriedDao extends AbstractVertxDAO<SysUserBuriedRecord, io.kida.model.tables.pojos.SysUserBuried, String, CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>>, CompletableFuture<io.kida.model.tables.pojos.SysUserBuried>, CompletableFuture<Integer>, CompletableFuture<String>> implements io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO<SysUserBuriedRecord,io.kida.model.tables.pojos.SysUserBuried,String> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public SysUserBuriedDao(Configuration configuration, io.vertx.core.Vertx vertx) {
        super(SysUserBuried.SYS_USER_BURIED, io.kida.model.tables.pojos.SysUserBuried.class, new JDBCCompletableFutureQueryExecutor<SysUserBuriedRecord,io.kida.model.tables.pojos.SysUserBuried,String>(configuration,io.kida.model.tables.pojos.SysUserBuried.class,vertx));
    }

    @Override
    protected String getId(io.kida.model.tables.pojos.SysUserBuried object) {
        return object.getId();
    }

    /**
     * Find records that have <code>IP IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByIp(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.IP.in(values));
    }

    /**
     * Find records that have <code>URI IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByUri(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.URI.in(values));
    }

    /**
     * Find records that have <code>SYS_CODE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyBySysCode(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.SYS_CODE.in(values));
    }

    /**
     * Find records that have <code>SSXT IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyBySsxt(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.SSXT.in(values));
    }

    /**
     * Find records that have <code>BUZZ_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByBuzzId(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.BUZZ_ID.in(values));
    }

    /**
     * Find records that have <code>ACCESS_DATE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByAccessDate(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.ACCESS_DATE.in(values));
    }

    /**
     * Find records that have <code>TYPE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByType(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.TYPE.in(values));
    }

    /**
     * Find records that have <code>DURATION_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByDurationTime(Collection<Long> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.DURATION_TIME.in(values));
    }

    /**
     * Find records that have <code>OPER_TYPE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByOperType(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.OPER_TYPE.in(values));
    }

    /**
     * Find records that have <code>ANALYSIS_LABEL IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByAnalysisLabel(Collection<String> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.ANALYSIS_LABEL.in(values));
    }

    /**
     * Find records that have <code>UID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserBuried>> findManyByUid(Collection<Long> values) {
        return findManyByCondition(SysUserBuried.SYS_USER_BURIED.UID.in(values));
    }

    @Override
    public JDBCCompletableFutureQueryExecutor<SysUserBuriedRecord,io.kida.model.tables.pojos.SysUserBuried,String> queryExecutor(){
        return (JDBCCompletableFutureQueryExecutor<SysUserBuriedRecord,io.kida.model.tables.pojos.SysUserBuried,String>) super.queryExecutor();
    }
}
