/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO;
import io.kida.model.tables.SysUserRole;
import io.kida.model.tables.records.SysUserRoleRecord;

import java.util.Collection;

import org.jooq.Configuration;
import org.jooq.Record2;


import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO;
import io.github.jklingsporn.vertx.jooq.completablefuture.jdbc.JDBCCompletableFutureQueryExecutor;
/**
 * 用户角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleDao extends AbstractVertxDAO<SysUserRoleRecord, io.kida.model.tables.pojos.SysUserRole, Record2<Long, Long>, CompletableFuture<List<io.kida.model.tables.pojos.SysUserRole>>, CompletableFuture<io.kida.model.tables.pojos.SysUserRole>, CompletableFuture<Integer>, CompletableFuture<Record2<Long, Long>>> implements io.github.jklingsporn.vertx.jooq.completablefuture.VertxDAO<SysUserRoleRecord,io.kida.model.tables.pojos.SysUserRole,Record2<Long, Long>> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public SysUserRoleDao(Configuration configuration, io.vertx.core.Vertx vertx) {
        super(SysUserRole.SYS_USER_ROLE, io.kida.model.tables.pojos.SysUserRole.class, new JDBCCompletableFutureQueryExecutor<SysUserRoleRecord,io.kida.model.tables.pojos.SysUserRole,Record2<Long, Long>>(configuration,io.kida.model.tables.pojos.SysUserRole.class,vertx));
    }

    @Override
    protected Record2<Long, Long> getId(io.kida.model.tables.pojos.SysUserRole object) {
        return compositeKeyRecord(object.getUserId(), object.getRoleId());
    }

    /**
     * Find records that have <code>ROLE_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<io.kida.model.tables.pojos.SysUserRole>> findManyByRoleId(Collection<Long> values) {
        return findManyByCondition(SysUserRole.SYS_USER_ROLE.ROLE_ID.in(values));
    }

    @Override
    public JDBCCompletableFutureQueryExecutor<SysUserRoleRecord,io.kida.model.tables.pojos.SysUserRole,Record2<Long, Long>> queryExecutor(){
        return (JDBCCompletableFutureQueryExecutor<SysUserRoleRecord,io.kida.model.tables.pojos.SysUserRole,Record2<Long, Long>>) super.queryExecutor();
    }
}
