/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 中医药达人题目爬取
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmmItembank implements VertxPojo, Serializable {

    private static final long serialVersionUID = -1580538688;

    private Long          id;
    private String        questionTitle;
    private String        optionA;
    private String        optionB;
    private String        optionC;
    private String        optionD;
    private String        optionE;
    private String        optionF;
    private LocalDateTime addTime;
    private String        acticleName;
    private Integer       pageNum;
    private Integer       subjectNum;

    public CmmItembank() {}

    public CmmItembank(CmmItembank value) {
        this.id = value.id;
        this.questionTitle = value.questionTitle;
        this.optionA = value.optionA;
        this.optionB = value.optionB;
        this.optionC = value.optionC;
        this.optionD = value.optionD;
        this.optionE = value.optionE;
        this.optionF = value.optionF;
        this.addTime = value.addTime;
        this.acticleName = value.acticleName;
        this.pageNum = value.pageNum;
        this.subjectNum = value.subjectNum;
    }

    public CmmItembank(
        Long          id,
        String        questionTitle,
        String        optionA,
        String        optionB,
        String        optionC,
        String        optionD,
        String        optionE,
        String        optionF,
        LocalDateTime addTime,
        String        acticleName,
        Integer       pageNum,
        Integer       subjectNum
    ) {
        this.id = id;
        this.questionTitle = questionTitle;
        this.optionA = optionA;
        this.optionB = optionB;
        this.optionC = optionC;
        this.optionD = optionD;
        this.optionE = optionE;
        this.optionF = optionF;
        this.addTime = addTime;
        this.acticleName = acticleName;
        this.pageNum = pageNum;
        this.subjectNum = subjectNum;
    }

    public Long getId() {
        return this.id;
    }

    public CmmItembank setId(Long id) {
        this.id = id;
        return this;
    }

    public String getQuestionTitle() {
        return this.questionTitle;
    }

    public CmmItembank setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
        return this;
    }

    public String getOptionA() {
        return this.optionA;
    }

    public CmmItembank setOptionA(String optionA) {
        this.optionA = optionA;
        return this;
    }

    public String getOptionB() {
        return this.optionB;
    }

    public CmmItembank setOptionB(String optionB) {
        this.optionB = optionB;
        return this;
    }

    public String getOptionC() {
        return this.optionC;
    }

    public CmmItembank setOptionC(String optionC) {
        this.optionC = optionC;
        return this;
    }

    public String getOptionD() {
        return this.optionD;
    }

    public CmmItembank setOptionD(String optionD) {
        this.optionD = optionD;
        return this;
    }

    public String getOptionE() {
        return this.optionE;
    }

    public CmmItembank setOptionE(String optionE) {
        this.optionE = optionE;
        return this;
    }

    public String getOptionF() {
        return this.optionF;
    }

    public CmmItembank setOptionF(String optionF) {
        this.optionF = optionF;
        return this;
    }

    public LocalDateTime getAddTime() {
        return this.addTime;
    }

    public CmmItembank setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
        return this;
    }

    public String getActicleName() {
        return this.acticleName;
    }

    public CmmItembank setActicleName(String acticleName) {
        this.acticleName = acticleName;
        return this;
    }

    public Integer getPageNum() {
        return this.pageNum;
    }

    public CmmItembank setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
        return this;
    }

    public Integer getSubjectNum() {
        return this.subjectNum;
    }

    public CmmItembank setSubjectNum(Integer subjectNum) {
        this.subjectNum = subjectNum;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CmmItembank (");

        sb.append(id);
        sb.append(", ").append(questionTitle);
        sb.append(", ").append(optionA);
        sb.append(", ").append(optionB);
        sb.append(", ").append(optionC);
        sb.append(", ").append(optionD);
        sb.append(", ").append(optionE);
        sb.append(", ").append(optionF);
        sb.append(", ").append(addTime);
        sb.append(", ").append(acticleName);
        sb.append(", ").append(pageNum);
        sb.append(", ").append(subjectNum);

        sb.append(")");
        return sb.toString();
    }

    public CmmItembank(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public CmmItembank fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.Long",e);
        }
        try {
            setQuestionTitle(json.getString("QUESTION_TITLE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("QUESTION_TITLE","java.lang.String",e);
        }
        try {
            setOptionA(json.getString("OPTION_A"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_A","java.lang.String",e);
        }
        try {
            setOptionB(json.getString("OPTION_B"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_B","java.lang.String",e);
        }
        try {
            setOptionC(json.getString("OPTION_C"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_C","java.lang.String",e);
        }
        try {
            setOptionD(json.getString("OPTION_D"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_D","java.lang.String",e);
        }
        try {
            setOptionE(json.getString("OPTION_E"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_E","java.lang.String",e);
        }
        try {
            setOptionF(json.getString("OPTION_F"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPTION_F","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ADD_TIME","java.time.LocalDateTime",e);
        }
        try {
            setActicleName(json.getString("ACTICLE_NAME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ACTICLE_NAME","java.lang.String",e);
        }
        try {
            setPageNum(json.getInteger("PAGE_NUM"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PAGE_NUM","java.lang.Integer",e);
        }
        try {
            setSubjectNum(json.getInteger("SUBJECT_NUM"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("SUBJECT_NUM","java.lang.Integer",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("QUESTION_TITLE",getQuestionTitle());
        json.put("OPTION_A",getOptionA());
        json.put("OPTION_B",getOptionB());
        json.put("OPTION_C",getOptionC());
        json.put("OPTION_D",getOptionD());
        json.put("OPTION_E",getOptionE());
        json.put("OPTION_F",getOptionF());
        // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        json.put("ACTICLE_NAME",getActicleName());
        json.put("PAGE_NUM",getPageNum());
        json.put("SUBJECT_NUM",getSubjectNum());
        return json;
    }

}
