/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * 方剂数据
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataPrescription implements VertxPojo, Serializable {

    private static final long serialVersionUID = -1864387089;

    private String drugName;
    private String variety;

    public DataPrescription() {}

    public DataPrescription(DataPrescription value) {
        this.drugName = value.drugName;
        this.variety = value.variety;
    }

    public DataPrescription(
        String drugName,
        String variety
    ) {
        this.drugName = drugName;
        this.variety = variety;
    }

    public String getDrugName() {
        return this.drugName;
    }

    public DataPrescription setDrugName(String drugName) {
        this.drugName = drugName;
        return this;
    }

    public String getVariety() {
        return this.variety;
    }

    public DataPrescription setVariety(String variety) {
        this.variety = variety;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataPrescription (");

        sb.append(drugName);
        sb.append(", ").append(variety);

        sb.append(")");
        return sb.toString();
    }

    public DataPrescription(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public DataPrescription fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setDrugName(json.getString("drug_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("drug_name","java.lang.String",e);
        }
        try {
            setVariety(json.getString("variety"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("variety","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("drug_name",getDrugName());
        json.put("variety",getVariety());
        return json;
    }

}
