/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * md5转换明文表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Md5Change implements VertxPojo, Serializable {

    private static final long serialVersionUID = 1476900804;

    private Long    id;
    private String  md5Code;
    private String  plainText;
    private Integer status;

    public Md5Change() {}

    public Md5Change(Md5Change value) {
        this.id = value.id;
        this.md5Code = value.md5Code;
        this.plainText = value.plainText;
        this.status = value.status;
    }

    public Md5Change(
        Long    id,
        String  md5Code,
        String  plainText,
        Integer status
    ) {
        this.id = id;
        this.md5Code = md5Code;
        this.plainText = plainText;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public Md5Change setId(Long id) {
        this.id = id;
        return this;
    }

    public String getMd5Code() {
        return this.md5Code;
    }

    public Md5Change setMd5Code(String md5Code) {
        this.md5Code = md5Code;
        return this;
    }

    public String getPlainText() {
        return this.plainText;
    }

    public Md5Change setPlainText(String plainText) {
        this.plainText = plainText;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public Md5Change setStatus(Integer status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Md5Change (");

        sb.append(id);
        sb.append(", ").append(md5Code);
        sb.append(", ").append(plainText);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    public Md5Change(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Md5Change fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.Long",e);
        }
        try {
            setMd5Code(json.getString("MD5_CODE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("MD5_CODE","java.lang.String",e);
        }
        try {
            setPlainText(json.getString("PLAIN_TEXT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PLAIN_TEXT","java.lang.String",e);
        }
        try {
            setStatus(json.getInteger("STATUS"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("STATUS","java.lang.Integer",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("MD5_CODE",getMd5Code());
        json.put("PLAIN_TEXT",getPlainText());
        json.put("STATUS",getStatus());
        return json;
    }

}
