/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 异常日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAbnormalLog implements VertxPojo, Serializable {

    private static final long serialVersionUID = 56020290;

    private Integer       id;
    private String        username;
    private String        url;
    private String        method;
    private String        params;
    private String        requestip;
    private String        detail;
    private LocalDateTime operDate;
    private Double        consumeTime;

    public SysAbnormalLog() {}

    public SysAbnormalLog(SysAbnormalLog value) {
        this.id = value.id;
        this.username = value.username;
        this.url = value.url;
        this.method = value.method;
        this.params = value.params;
        this.requestip = value.requestip;
        this.detail = value.detail;
        this.operDate = value.operDate;
        this.consumeTime = value.consumeTime;
    }

    public SysAbnormalLog(
        Integer       id,
        String        username,
        String        url,
        String        method,
        String        params,
        String        requestip,
        String        detail,
        LocalDateTime operDate,
        Double        consumeTime
    ) {
        this.id = id;
        this.username = username;
        this.url = url;
        this.method = method;
        this.params = params;
        this.requestip = requestip;
        this.detail = detail;
        this.operDate = operDate;
        this.consumeTime = consumeTime;
    }

    public Integer getId() {
        return this.id;
    }

    public SysAbnormalLog setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public SysAbnormalLog setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public SysAbnormalLog setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getMethod() {
        return this.method;
    }

    public SysAbnormalLog setMethod(String method) {
        this.method = method;
        return this;
    }

    public String getParams() {
        return this.params;
    }

    public SysAbnormalLog setParams(String params) {
        this.params = params;
        return this;
    }

    public String getRequestip() {
        return this.requestip;
    }

    public SysAbnormalLog setRequestip(String requestip) {
        this.requestip = requestip;
        return this;
    }

    public String getDetail() {
        return this.detail;
    }

    public SysAbnormalLog setDetail(String detail) {
        this.detail = detail;
        return this;
    }

    public LocalDateTime getOperDate() {
        return this.operDate;
    }

    public SysAbnormalLog setOperDate(LocalDateTime operDate) {
        this.operDate = operDate;
        return this;
    }

    public Double getConsumeTime() {
        return this.consumeTime;
    }

    public SysAbnormalLog setConsumeTime(Double consumeTime) {
        this.consumeTime = consumeTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysAbnormalLog (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(url);
        sb.append(", ").append(method);
        sb.append(", ").append(params);
        sb.append(", ").append(requestip);
        sb.append(", ").append(detail);
        sb.append(", ").append(operDate);
        sb.append(", ").append(consumeTime);

        sb.append(")");
        return sb.toString();
    }

    public SysAbnormalLog(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysAbnormalLog fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getInteger("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.Integer",e);
        }
        try {
            setUsername(json.getString("USERNAME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USERNAME","java.lang.String",e);
        }
        try {
            setUrl(json.getString("URL"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("URL","java.lang.String",e);
        }
        try {
            setMethod(json.getString("METHOD"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("METHOD","java.lang.String",e);
        }
        try {
            setParams(json.getString("PARAMS"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PARAMS","java.lang.String",e);
        }
        try {
            setRequestip(json.getString("REQUESTIP"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("REQUESTIP","java.lang.String",e);
        }
        try {
            setDetail(json.getString("DETAIL"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("DETAIL","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column OPER_DATE!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_DATE","java.time.LocalDateTime",e);
        }
        try {
            setConsumeTime(json.getDouble("CONSUME_TIME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("CONSUME_TIME","java.lang.Double",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("USERNAME",getUsername());
        json.put("URL",getUrl());
        json.put("METHOD",getMethod());
        json.put("PARAMS",getParams());
        json.put("REQUESTIP",getRequestip());
        json.put("DETAIL",getDetail());
        // Omitting unrecognized type java.time.LocalDateTime for column OPER_DATE!
        json.put("CONSUME_TIME",getConsumeTime());
        return json;
    }

}
