/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * 数据字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDataDict implements VertxPojo, Serializable {

    private static final long serialVersionUID = -1767176045;

    private String did;
    private String parentId;
    private String dcode;
    private String dname;

    public SysDataDict() {}

    public SysDataDict(SysDataDict value) {
        this.did = value.did;
        this.parentId = value.parentId;
        this.dcode = value.dcode;
        this.dname = value.dname;
    }

    public SysDataDict(
        String did,
        String parentId,
        String dcode,
        String dname
    ) {
        this.did = did;
        this.parentId = parentId;
        this.dcode = dcode;
        this.dname = dname;
    }

    public String getDid() {
        return this.did;
    }

    public SysDataDict setDid(String did) {
        this.did = did;
        return this;
    }

    public String getParentId() {
        return this.parentId;
    }

    public SysDataDict setParentId(String parentId) {
        this.parentId = parentId;
        return this;
    }

    public String getDcode() {
        return this.dcode;
    }

    public SysDataDict setDcode(String dcode) {
        this.dcode = dcode;
        return this;
    }

    public String getDname() {
        return this.dname;
    }

    public SysDataDict setDname(String dname) {
        this.dname = dname;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDataDict (");

        sb.append(did);
        sb.append(", ").append(parentId);
        sb.append(", ").append(dcode);
        sb.append(", ").append(dname);

        sb.append(")");
        return sb.toString();
    }

    public SysDataDict(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysDataDict fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setDid(json.getString("did"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("did","java.lang.String",e);
        }
        try {
            setParentId(json.getString("parent_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("parent_id","java.lang.String",e);
        }
        try {
            setDcode(json.getString("dcode"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("dcode","java.lang.String",e);
        }
        try {
            setDname(json.getString("dname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("dname","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("did",getDid());
        json.put("parent_id",getParentId());
        json.put("dcode",getDcode());
        json.put("dname",getDname());
        return json;
    }

}
