/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 系统操作记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOperRecord implements VertxPojo, Serializable {

    private static final long serialVersionUID = -864323340;

    private Long          operId;
    private Long          userId;
    private String        operPage;
    private LocalDateTime operTime;
    private String        operBeforeJson;
    private String        operAfterJson;
    private String        operContent;

    public SysOperRecord() {}

    public SysOperRecord(SysOperRecord value) {
        this.operId = value.operId;
        this.userId = value.userId;
        this.operPage = value.operPage;
        this.operTime = value.operTime;
        this.operBeforeJson = value.operBeforeJson;
        this.operAfterJson = value.operAfterJson;
        this.operContent = value.operContent;
    }

    public SysOperRecord(
        Long          operId,
        Long          userId,
        String        operPage,
        LocalDateTime operTime,
        String        operBeforeJson,
        String        operAfterJson,
        String        operContent
    ) {
        this.operId = operId;
        this.userId = userId;
        this.operPage = operPage;
        this.operTime = operTime;
        this.operBeforeJson = operBeforeJson;
        this.operAfterJson = operAfterJson;
        this.operContent = operContent;
    }

    public Long getOperId() {
        return this.operId;
    }

    public SysOperRecord setOperId(Long operId) {
        this.operId = operId;
        return this;
    }

    public Long getUserId() {
        return this.userId;
    }

    public SysOperRecord setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    public String getOperPage() {
        return this.operPage;
    }

    public SysOperRecord setOperPage(String operPage) {
        this.operPage = operPage;
        return this;
    }

    public LocalDateTime getOperTime() {
        return this.operTime;
    }

    public SysOperRecord setOperTime(LocalDateTime operTime) {
        this.operTime = operTime;
        return this;
    }

    public String getOperBeforeJson() {
        return this.operBeforeJson;
    }

    public SysOperRecord setOperBeforeJson(String operBeforeJson) {
        this.operBeforeJson = operBeforeJson;
        return this;
    }

    public String getOperAfterJson() {
        return this.operAfterJson;
    }

    public SysOperRecord setOperAfterJson(String operAfterJson) {
        this.operAfterJson = operAfterJson;
        return this;
    }

    public String getOperContent() {
        return this.operContent;
    }

    public SysOperRecord setOperContent(String operContent) {
        this.operContent = operContent;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysOperRecord (");

        sb.append(operId);
        sb.append(", ").append(userId);
        sb.append(", ").append(operPage);
        sb.append(", ").append(operTime);
        sb.append(", ").append(operBeforeJson);
        sb.append(", ").append(operAfterJson);
        sb.append(", ").append(operContent);

        sb.append(")");
        return sb.toString();
    }

    public SysOperRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysOperRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setOperId(json.getLong("OPER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_ID","java.lang.Long",e);
        }
        try {
            setUserId(json.getLong("USER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_ID","java.lang.Long",e);
        }
        try {
            setOperPage(json.getString("OPER_PAGE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_PAGE","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column OPER_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_TIME","java.time.LocalDateTime",e);
        }
        try {
            setOperBeforeJson(json.getString("OPER_BEFORE_JSON"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_BEFORE_JSON","java.lang.String",e);
        }
        try {
            setOperAfterJson(json.getString("OPER_AFTER_JSON"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_AFTER_JSON","java.lang.String",e);
        }
        try {
            setOperContent(json.getString("OPER_CONTENT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_CONTENT","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("OPER_ID",getOperId());
        json.put("USER_ID",getUserId());
        json.put("OPER_PAGE",getOperPage());
        // Omitting unrecognized type java.time.LocalDateTime for column OPER_TIME!
        json.put("OPER_BEFORE_JSON",getOperBeforeJson());
        json.put("OPER_AFTER_JSON",getOperAfterJson());
        json.put("OPER_CONTENT",getOperContent());
        return json;
    }

}
