/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * 权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermission implements VertxPojo, Serializable {

    private static final long serialVersionUID = 198867286;

    private Long    permissionId;
    private Long    pPermissionId;
    private String  permissionName;
    private Integer permissionType;
    private Integer showFlag;
    private String  remark;

    public SysPermission() {}

    public SysPermission(SysPermission value) {
        this.permissionId = value.permissionId;
        this.pPermissionId = value.pPermissionId;
        this.permissionName = value.permissionName;
        this.permissionType = value.permissionType;
        this.showFlag = value.showFlag;
        this.remark = value.remark;
    }

    public SysPermission(
        Long    permissionId,
        Long    pPermissionId,
        String  permissionName,
        Integer permissionType,
        Integer showFlag,
        String  remark
    ) {
        this.permissionId = permissionId;
        this.pPermissionId = pPermissionId;
        this.permissionName = permissionName;
        this.permissionType = permissionType;
        this.showFlag = showFlag;
        this.remark = remark;
    }

    public Long getPermissionId() {
        return this.permissionId;
    }

    public SysPermission setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
        return this;
    }

    public Long getPPermissionId() {
        return this.pPermissionId;
    }

    public SysPermission setPPermissionId(Long pPermissionId) {
        this.pPermissionId = pPermissionId;
        return this;
    }

    public String getPermissionName() {
        return this.permissionName;
    }

    public SysPermission setPermissionName(String permissionName) {
        this.permissionName = permissionName;
        return this;
    }

    public Integer getPermissionType() {
        return this.permissionType;
    }

    public SysPermission setPermissionType(Integer permissionType) {
        this.permissionType = permissionType;
        return this;
    }

    public Integer getShowFlag() {
        return this.showFlag;
    }

    public SysPermission setShowFlag(Integer showFlag) {
        this.showFlag = showFlag;
        return this;
    }

    public String getRemark() {
        return this.remark;
    }

    public SysPermission setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermission (");

        sb.append(permissionId);
        sb.append(", ").append(pPermissionId);
        sb.append(", ").append(permissionName);
        sb.append(", ").append(permissionType);
        sb.append(", ").append(showFlag);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }

    public SysPermission(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysPermission fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setPermissionId(json.getLong("PERMISSION_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PERMISSION_ID","java.lang.Long",e);
        }
        try {
            setPPermissionId(json.getLong("P_PERMISSION_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("P_PERMISSION_ID","java.lang.Long",e);
        }
        try {
            setPermissionName(json.getString("PERMISSION_NAME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PERMISSION_NAME","java.lang.String",e);
        }
        try {
            setPermissionType(json.getInteger("PERMISSION_TYPE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PERMISSION_TYPE","java.lang.Integer",e);
        }
        try {
            setShowFlag(json.getInteger("SHOW_FLAG"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("SHOW_FLAG","java.lang.Integer",e);
        }
        try {
            setRemark(json.getString("REMARK"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("REMARK","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("PERMISSION_ID",getPermissionId());
        json.put("P_PERMISSION_ID",getPPermissionId());
        json.put("PERMISSION_NAME",getPermissionName());
        json.put("PERMISSION_TYPE",getPermissionType());
        json.put("SHOW_FLAG",getShowFlag());
        json.put("REMARK",getRemark());
        return json;
    }

}
