/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * 用户信息埋点表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserBuried implements VertxPojo, Serializable {

    private static final long serialVersionUID = 2057768342;

    private String id;
    private String ip;
    private String uri;
    private String sysCode;
    private String ssxt;
    private String buzzId;
    private String accessDate;
    private String type;
    private Long   durationTime;
    private String operType;
    private String analysisLabel;
    private Long   uid;

    public SysUserBuried() {}

    public SysUserBuried(SysUserBuried value) {
        this.id = value.id;
        this.ip = value.ip;
        this.uri = value.uri;
        this.sysCode = value.sysCode;
        this.ssxt = value.ssxt;
        this.buzzId = value.buzzId;
        this.accessDate = value.accessDate;
        this.type = value.type;
        this.durationTime = value.durationTime;
        this.operType = value.operType;
        this.analysisLabel = value.analysisLabel;
        this.uid = value.uid;
    }

    public SysUserBuried(
        String id,
        String ip,
        String uri,
        String sysCode,
        String ssxt,
        String buzzId,
        String accessDate,
        String type,
        Long   durationTime,
        String operType,
        String analysisLabel,
        Long   uid
    ) {
        this.id = id;
        this.ip = ip;
        this.uri = uri;
        this.sysCode = sysCode;
        this.ssxt = ssxt;
        this.buzzId = buzzId;
        this.accessDate = accessDate;
        this.type = type;
        this.durationTime = durationTime;
        this.operType = operType;
        this.analysisLabel = analysisLabel;
        this.uid = uid;
    }

    public String getId() {
        return this.id;
    }

    public SysUserBuried setId(String id) {
        this.id = id;
        return this;
    }

    public String getIp() {
        return this.ip;
    }

    public SysUserBuried setIp(String ip) {
        this.ip = ip;
        return this;
    }

    public String getUri() {
        return this.uri;
    }

    public SysUserBuried setUri(String uri) {
        this.uri = uri;
        return this;
    }

    public String getSysCode() {
        return this.sysCode;
    }

    public SysUserBuried setSysCode(String sysCode) {
        this.sysCode = sysCode;
        return this;
    }

    public String getSsxt() {
        return this.ssxt;
    }

    public SysUserBuried setSsxt(String ssxt) {
        this.ssxt = ssxt;
        return this;
    }

    public String getBuzzId() {
        return this.buzzId;
    }

    public SysUserBuried setBuzzId(String buzzId) {
        this.buzzId = buzzId;
        return this;
    }

    public String getAccessDate() {
        return this.accessDate;
    }

    public SysUserBuried setAccessDate(String accessDate) {
        this.accessDate = accessDate;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public SysUserBuried setType(String type) {
        this.type = type;
        return this;
    }

    public Long getDurationTime() {
        return this.durationTime;
    }

    public SysUserBuried setDurationTime(Long durationTime) {
        this.durationTime = durationTime;
        return this;
    }

    public String getOperType() {
        return this.operType;
    }

    public SysUserBuried setOperType(String operType) {
        this.operType = operType;
        return this;
    }

    public String getAnalysisLabel() {
        return this.analysisLabel;
    }

    public SysUserBuried setAnalysisLabel(String analysisLabel) {
        this.analysisLabel = analysisLabel;
        return this;
    }

    public Long getUid() {
        return this.uid;
    }

    public SysUserBuried setUid(Long uid) {
        this.uid = uid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserBuried (");

        sb.append(id);
        sb.append(", ").append(ip);
        sb.append(", ").append(uri);
        sb.append(", ").append(sysCode);
        sb.append(", ").append(ssxt);
        sb.append(", ").append(buzzId);
        sb.append(", ").append(accessDate);
        sb.append(", ").append(type);
        sb.append(", ").append(durationTime);
        sb.append(", ").append(operType);
        sb.append(", ").append(analysisLabel);
        sb.append(", ").append(uid);

        sb.append(")");
        return sb.toString();
    }

    public SysUserBuried(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysUserBuried fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getString("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.String",e);
        }
        try {
            setIp(json.getString("IP"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("IP","java.lang.String",e);
        }
        try {
            setUri(json.getString("URI"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("URI","java.lang.String",e);
        }
        try {
            setSysCode(json.getString("SYS_CODE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("SYS_CODE","java.lang.String",e);
        }
        try {
            setSsxt(json.getString("SSXT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("SSXT","java.lang.String",e);
        }
        try {
            setBuzzId(json.getString("BUZZ_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("BUZZ_ID","java.lang.String",e);
        }
        try {
            setAccessDate(json.getString("ACCESS_DATE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ACCESS_DATE","java.lang.String",e);
        }
        try {
            setType(json.getString("TYPE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("TYPE","java.lang.String",e);
        }
        try {
            setDurationTime(json.getLong("DURATION_TIME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("DURATION_TIME","java.lang.Long",e);
        }
        try {
            setOperType(json.getString("OPER_TYPE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_TYPE","java.lang.String",e);
        }
        try {
            setAnalysisLabel(json.getString("ANALYSIS_LABEL"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ANALYSIS_LABEL","java.lang.String",e);
        }
        try {
            setUid(json.getLong("UID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("UID","java.lang.Long",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("IP",getIp());
        json.put("URI",getUri());
        json.put("SYS_CODE",getSysCode());
        json.put("SSXT",getSsxt());
        json.put("BUZZ_ID",getBuzzId());
        json.put("ACCESS_DATE",getAccessDate());
        json.put("TYPE",getType());
        json.put("DURATION_TIME",getDurationTime());
        json.put("OPER_TYPE",getOperType());
        json.put("ANALYSIS_LABEL",getAnalysisLabel());
        json.put("UID",getUid());
        return json;
    }

}
