/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.DataVarietyEnterprice;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * 品种与企业对应数据
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataVarietyEnterpriceRecord extends TableRecordImpl<DataVarietyEnterpriceRecord> implements VertxPojo, Record8<String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -929634107;

    /**
     * Setter for <code>tools.data_variety_enterprice.variety</code>. 药品品种
     */
    public DataVarietyEnterpriceRecord setVariety(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.variety</code>. 药品品种
     */
    public String getVariety() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.enterprice</code>. 药企名称
     */
    public DataVarietyEnterpriceRecord setEnterprice(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.enterprice</code>. 药企名称
     */
    public String getEnterprice() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.enterprice_role</code>. 药企角色
     */
    public DataVarietyEnterpriceRecord setEnterpriceRole(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.enterprice_role</code>. 药企角色
     */
    public String getEnterpriceRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.email</code>. 电子邮箱
     */
    public DataVarietyEnterpriceRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.email</code>. 电子邮箱
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.contact_phone</code>. 联系电话
     */
    public DataVarietyEnterpriceRecord setContactPhone(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.contact_phone</code>. 联系电话
     */
    public String getContactPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.company_address</code>. 联系地址
     */
    public DataVarietyEnterpriceRecord setCompanyAddress(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.company_address</code>. 联系地址
     */
    public String getCompanyAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.contact_name</code>. 联系人
     */
    public DataVarietyEnterpriceRecord setContactName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.contact_name</code>. 联系人
     */
    public String getContactName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tools.data_variety_enterprice.variety_type</code>. 品种类型
     */
    public DataVarietyEnterpriceRecord setVarietyType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_variety_enterprice.variety_type</code>. 品种类型
     */
    public String getVarietyType() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.VARIETY;
    }

    @Override
    public Field<String> field2() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.ENTERPRICE;
    }

    @Override
    public Field<String> field3() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.ENTERPRICE_ROLE;
    }

    @Override
    public Field<String> field4() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.CONTACT_PHONE;
    }

    @Override
    public Field<String> field6() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.COMPANY_ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.CONTACT_NAME;
    }

    @Override
    public Field<String> field8() {
        return DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE.VARIETY_TYPE;
    }

    @Override
    public String component1() {
        return getVariety();
    }

    @Override
    public String component2() {
        return getEnterprice();
    }

    @Override
    public String component3() {
        return getEnterpriceRole();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getContactPhone();
    }

    @Override
    public String component6() {
        return getCompanyAddress();
    }

    @Override
    public String component7() {
        return getContactName();
    }

    @Override
    public String component8() {
        return getVarietyType();
    }

    @Override
    public String value1() {
        return getVariety();
    }

    @Override
    public String value2() {
        return getEnterprice();
    }

    @Override
    public String value3() {
        return getEnterpriceRole();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getContactPhone();
    }

    @Override
    public String value6() {
        return getCompanyAddress();
    }

    @Override
    public String value7() {
        return getContactName();
    }

    @Override
    public String value8() {
        return getVarietyType();
    }

    @Override
    public DataVarietyEnterpriceRecord value1(String value) {
        setVariety(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value2(String value) {
        setEnterprice(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value3(String value) {
        setEnterpriceRole(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value5(String value) {
        setContactPhone(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value6(String value) {
        setCompanyAddress(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value7(String value) {
        setContactName(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord value8(String value) {
        setVarietyType(value);
        return this;
    }

    @Override
    public DataVarietyEnterpriceRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataVarietyEnterpriceRecord
     */
    public DataVarietyEnterpriceRecord() {
        super(DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE);
    }

    /**
     * Create a detached, initialised DataVarietyEnterpriceRecord
     */
    public DataVarietyEnterpriceRecord(String variety, String enterprice, String enterpriceRole, String email, String contactPhone, String companyAddress, String contactName, String varietyType) {
        super(DataVarietyEnterprice.DATA_VARIETY_ENTERPRICE);

        set(0, variety);
        set(1, enterprice);
        set(2, enterpriceRole);
        set(3, email);
        set(4, contactPhone);
        set(5, companyAddress);
        set(6, contactName);
        set(7, varietyType);
    }

    public DataVarietyEnterpriceRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public DataVarietyEnterpriceRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setVariety(json.getString("variety"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("variety","java.lang.String",e);
        }
        try {
            setEnterprice(json.getString("enterprice"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("enterprice","java.lang.String",e);
        }
        try {
            setEnterpriceRole(json.getString("enterprice_role"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("enterprice_role","java.lang.String",e);
        }
        try {
            setEmail(json.getString("email"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("email","java.lang.String",e);
        }
        try {
            setContactPhone(json.getString("contact_phone"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("contact_phone","java.lang.String",e);
        }
        try {
            setCompanyAddress(json.getString("company_address"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("company_address","java.lang.String",e);
        }
        try {
            setContactName(json.getString("contact_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("contact_name","java.lang.String",e);
        }
        try {
            setVarietyType(json.getString("variety_type"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("variety_type","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("variety",getVariety());
        json.put("enterprice",getEnterprice());
        json.put("enterprice_role",getEnterpriceRole());
        json.put("email",getEmail());
        json.put("contact_phone",getContactPhone());
        json.put("company_address",getCompanyAddress());
        json.put("contact_name",getContactName());
        json.put("variety_type",getVarietyType());
        return json;
    }

}
