/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.DataAssociation;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * 数据关联
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataAssociationRecord extends TableRecordImpl<DataAssociationRecord> implements VertxPojo, Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 730557959;

    /**
     * Setter for <code>tools.data_association.drug_name</code>. 国产药品名称
     */
    public DataAssociationRecord setDrugName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_association.drug_name</code>. 国产药品名称
     */
    public String getDrugName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tools.data_association.approval_number</code>.
     */
    public DataAssociationRecord setApprovalNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_association.approval_number</code>.
     */
    public String getApprovalNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tools.data_association.production_unit</code>. 生产单位
     */
    public DataAssociationRecord setProductionUnit(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_association.production_unit</code>. 生产单位
     */
    public String getProductionUnit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.data_association.preparation</code>. 制剂
     */
    public DataAssociationRecord setPreparation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_association.preparation</code>. 制剂
     */
    public String getPreparation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tools.data_association.specifications</code>. 规格
     */
    public DataAssociationRecord setSpecifications(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tools.data_association.specifications</code>. 规格
     */
    public String getSpecifications() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DataAssociation.DATA_ASSOCIATION.DRUG_NAME;
    }

    @Override
    public Field<String> field2() {
        return DataAssociation.DATA_ASSOCIATION.APPROVAL_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return DataAssociation.DATA_ASSOCIATION.PRODUCTION_UNIT;
    }

    @Override
    public Field<String> field4() {
        return DataAssociation.DATA_ASSOCIATION.PREPARATION;
    }

    @Override
    public Field<String> field5() {
        return DataAssociation.DATA_ASSOCIATION.SPECIFICATIONS;
    }

    @Override
    public String component1() {
        return getDrugName();
    }

    @Override
    public String component2() {
        return getApprovalNumber();
    }

    @Override
    public String component3() {
        return getProductionUnit();
    }

    @Override
    public String component4() {
        return getPreparation();
    }

    @Override
    public String component5() {
        return getSpecifications();
    }

    @Override
    public String value1() {
        return getDrugName();
    }

    @Override
    public String value2() {
        return getApprovalNumber();
    }

    @Override
    public String value3() {
        return getProductionUnit();
    }

    @Override
    public String value4() {
        return getPreparation();
    }

    @Override
    public String value5() {
        return getSpecifications();
    }

    @Override
    public DataAssociationRecord value1(String value) {
        setDrugName(value);
        return this;
    }

    @Override
    public DataAssociationRecord value2(String value) {
        setApprovalNumber(value);
        return this;
    }

    @Override
    public DataAssociationRecord value3(String value) {
        setProductionUnit(value);
        return this;
    }

    @Override
    public DataAssociationRecord value4(String value) {
        setPreparation(value);
        return this;
    }

    @Override
    public DataAssociationRecord value5(String value) {
        setSpecifications(value);
        return this;
    }

    @Override
    public DataAssociationRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataAssociationRecord
     */
    public DataAssociationRecord() {
        super(DataAssociation.DATA_ASSOCIATION);
    }

    /**
     * Create a detached, initialised DataAssociationRecord
     */
    public DataAssociationRecord(String drugName, String approvalNumber, String productionUnit, String preparation, String specifications) {
        super(DataAssociation.DATA_ASSOCIATION);

        set(0, drugName);
        set(1, approvalNumber);
        set(2, productionUnit);
        set(3, preparation);
        set(4, specifications);
    }

    public DataAssociationRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public DataAssociationRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setDrugName(json.getString("drug_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("drug_name","java.lang.String",e);
        }
        try {
            setApprovalNumber(json.getString("approval_number"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("approval_number","java.lang.String",e);
        }
        try {
            setProductionUnit(json.getString("production_unit"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("production_unit","java.lang.String",e);
        }
        try {
            setPreparation(json.getString("preparation"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("preparation","java.lang.String",e);
        }
        try {
            setSpecifications(json.getString("specifications"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("specifications","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("drug_name",getDrugName());
        json.put("approval_number",getApprovalNumber());
        json.put("production_unit",getProductionUnit());
        json.put("preparation",getPreparation());
        json.put("specifications",getSpecifications());
        return json;
    }

}
