/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.Md5Change;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * md5转换明文表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Md5ChangeRecord extends UpdatableRecordImpl<Md5ChangeRecord> implements VertxPojo, Record4<Long, String, String, Integer> {

    private static final long serialVersionUID = -325285709;

    /**
     * Setter for <code>tools.md5_change.ID</code>. id值
     */
    public Md5ChangeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.md5_change.ID</code>. id值
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tools.md5_change.MD5_CODE</code>. md5编码
     */
    public Md5ChangeRecord setMd5Code(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.md5_change.MD5_CODE</code>. md5编码
     */
    public String getMd5Code() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tools.md5_change.PLAIN_TEXT</code>. 明文
     */
    public Md5ChangeRecord setPlainText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.md5_change.PLAIN_TEXT</code>. 明文
     */
    public String getPlainText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.md5_change.STATUS</code>. 0:未转 1:已转
     */
    public Md5ChangeRecord setStatus(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.md5_change.STATUS</code>. 0:未转 1:已转
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Md5Change.MD5_CHANGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Md5Change.MD5_CHANGE.MD5_CODE;
    }

    @Override
    public Field<String> field3() {
        return Md5Change.MD5_CHANGE.PLAIN_TEXT;
    }

    @Override
    public Field<Integer> field4() {
        return Md5Change.MD5_CHANGE.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMd5Code();
    }

    @Override
    public String component3() {
        return getPlainText();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMd5Code();
    }

    @Override
    public String value3() {
        return getPlainText();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public Md5ChangeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public Md5ChangeRecord value2(String value) {
        setMd5Code(value);
        return this;
    }

    @Override
    public Md5ChangeRecord value3(String value) {
        setPlainText(value);
        return this;
    }

    @Override
    public Md5ChangeRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public Md5ChangeRecord values(Long value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Md5ChangeRecord
     */
    public Md5ChangeRecord() {
        super(Md5Change.MD5_CHANGE);
    }

    /**
     * Create a detached, initialised Md5ChangeRecord
     */
    public Md5ChangeRecord(Long id, String md5Code, String plainText, Integer status) {
        super(Md5Change.MD5_CHANGE);

        set(0, id);
        set(1, md5Code);
        set(2, plainText);
        set(3, status);
    }

    public Md5ChangeRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Md5ChangeRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.Long",e);
        }
        try {
            setMd5Code(json.getString("MD5_CODE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("MD5_CODE","java.lang.String",e);
        }
        try {
            setPlainText(json.getString("PLAIN_TEXT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PLAIN_TEXT","java.lang.String",e);
        }
        try {
            setStatus(json.getInteger("STATUS"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("STATUS","java.lang.Integer",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("MD5_CODE",getMd5Code());
        json.put("PLAIN_TEXT",getPlainText());
        json.put("STATUS",getStatus());
        return json;
    }

}
