/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.SysOperRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统操作记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOperRecordRecord extends UpdatableRecordImpl<SysOperRecordRecord> implements VertxPojo, Record7<Long, Long, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = -1833370698;

    /**
     * Setter for <code>tools.sys_oper_record.OPER_ID</code>. 操作id
     */
    public SysOperRecordRecord setOperId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_ID</code>. 操作id
     */
    public Long getOperId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tools.sys_oper_record.USER_ID</code>. 用户id
     */
    public SysOperRecordRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.USER_ID</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>tools.sys_oper_record.OPER_PAGE</code>. 操作页面url地址
     */
    public SysOperRecordRecord setOperPage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_PAGE</code>. 操作页面url地址
     */
    public String getOperPage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.sys_oper_record.OPER_TIME</code>. 操作时间
     */
    public SysOperRecordRecord setOperTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_TIME</code>. 操作时间
     */
    public LocalDateTime getOperTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>tools.sys_oper_record.OPER_BEFORE_JSON</code>. 操作前json信息
     */
    public SysOperRecordRecord setOperBeforeJson(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_BEFORE_JSON</code>. 操作前json信息
     */
    public String getOperBeforeJson() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tools.sys_oper_record.OPER_AFTER_JSON</code>. 操作后json信息
     */
    public SysOperRecordRecord setOperAfterJson(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_AFTER_JSON</code>. 操作后json信息
     */
    public String getOperAfterJson() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tools.sys_oper_record.OPER_CONTENT</code>. 操作中文记录
     */
    public SysOperRecordRecord setOperContent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_oper_record.OPER_CONTENT</code>. 操作中文记录
     */
    public String getOperContent() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_ID;
    }

    @Override
    public Field<Long> field2() {
        return SysOperRecord.SYS_OPER_RECORD.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_PAGE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_TIME;
    }

    @Override
    public Field<String> field5() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_BEFORE_JSON;
    }

    @Override
    public Field<String> field6() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_AFTER_JSON;
    }

    @Override
    public Field<String> field7() {
        return SysOperRecord.SYS_OPER_RECORD.OPER_CONTENT;
    }

    @Override
    public Long component1() {
        return getOperId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getOperPage();
    }

    @Override
    public LocalDateTime component4() {
        return getOperTime();
    }

    @Override
    public String component5() {
        return getOperBeforeJson();
    }

    @Override
    public String component6() {
        return getOperAfterJson();
    }

    @Override
    public String component7() {
        return getOperContent();
    }

    @Override
    public Long value1() {
        return getOperId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getOperPage();
    }

    @Override
    public LocalDateTime value4() {
        return getOperTime();
    }

    @Override
    public String value5() {
        return getOperBeforeJson();
    }

    @Override
    public String value6() {
        return getOperAfterJson();
    }

    @Override
    public String value7() {
        return getOperContent();
    }

    @Override
    public SysOperRecordRecord value1(Long value) {
        setOperId(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value3(String value) {
        setOperPage(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value4(LocalDateTime value) {
        setOperTime(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value5(String value) {
        setOperBeforeJson(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value6(String value) {
        setOperAfterJson(value);
        return this;
    }

    @Override
    public SysOperRecordRecord value7(String value) {
        setOperContent(value);
        return this;
    }

    @Override
    public SysOperRecordRecord values(Long value1, Long value2, String value3, LocalDateTime value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOperRecordRecord
     */
    public SysOperRecordRecord() {
        super(SysOperRecord.SYS_OPER_RECORD);
    }

    /**
     * Create a detached, initialised SysOperRecordRecord
     */
    public SysOperRecordRecord(Long operId, Long userId, String operPage, LocalDateTime operTime, String operBeforeJson, String operAfterJson, String operContent) {
        super(SysOperRecord.SYS_OPER_RECORD);

        set(0, operId);
        set(1, userId);
        set(2, operPage);
        set(3, operTime);
        set(4, operBeforeJson);
        set(5, operAfterJson);
        set(6, operContent);
    }

    public SysOperRecordRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysOperRecordRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setOperId(json.getLong("OPER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_ID","java.lang.Long",e);
        }
        try {
            setUserId(json.getLong("USER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_ID","java.lang.Long",e);
        }
        try {
            setOperPage(json.getString("OPER_PAGE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_PAGE","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column OPER_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_TIME","java.time.LocalDateTime",e);
        }
        try {
            setOperBeforeJson(json.getString("OPER_BEFORE_JSON"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_BEFORE_JSON","java.lang.String",e);
        }
        try {
            setOperAfterJson(json.getString("OPER_AFTER_JSON"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_AFTER_JSON","java.lang.String",e);
        }
        try {
            setOperContent(json.getString("OPER_CONTENT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPER_CONTENT","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("OPER_ID",getOperId());
        json.put("USER_ID",getUserId());
        json.put("OPER_PAGE",getOperPage());
        // Omitting unrecognized type java.time.LocalDateTime for column OPER_TIME!
        json.put("OPER_BEFORE_JSON",getOperBeforeJson());
        json.put("OPER_AFTER_JSON",getOperAfterJson());
        json.put("OPER_CONTENT",getOperContent());
        return json;
    }

}
