/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.SysRolePermission;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色权限关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRolePermissionRecord extends UpdatableRecordImpl<SysRolePermissionRecord> implements VertxPojo, Record2<Long, Long> {

    private static final long serialVersionUID = 1652924361;

    /**
     * Setter for <code>tools.sys_role_permission.ROLE_ID</code>. 角色编号
     */
    public SysRolePermissionRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role_permission.ROLE_ID</code>. 角色编号
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tools.sys_role_permission.PERMISSION_ID</code>. 权限编号
     */
    public SysRolePermissionRecord setPermissionId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role_permission.PERMISSION_ID</code>. 权限编号
     */
    public Long getPermissionId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysRolePermission.SYS_ROLE_PERMISSION.ROLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return SysRolePermission.SYS_ROLE_PERMISSION.PERMISSION_ID;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public Long component2() {
        return getPermissionId();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public Long value2() {
        return getPermissionId();
    }

    @Override
    public SysRolePermissionRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysRolePermissionRecord value2(Long value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public SysRolePermissionRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRolePermissionRecord
     */
    public SysRolePermissionRecord() {
        super(SysRolePermission.SYS_ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised SysRolePermissionRecord
     */
    public SysRolePermissionRecord(Long roleId, Long permissionId) {
        super(SysRolePermission.SYS_ROLE_PERMISSION);

        set(0, roleId);
        set(1, permissionId);
    }

    public SysRolePermissionRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysRolePermissionRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setRoleId(json.getLong("ROLE_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ROLE_ID","java.lang.Long",e);
        }
        try {
            setPermissionId(json.getLong("PERMISSION_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PERMISSION_ID","java.lang.Long",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ROLE_ID",getRoleId());
        json.put("PERMISSION_ID",getPermissionId());
        return json;
    }

}
