/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.SysRole;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements VertxPojo, Record9<Long, String, String, Integer, Long, LocalDateTime, Long, LocalDateTime, Integer> {

    private static final long serialVersionUID = -1212439130;

    /**
     * Setter for <code>tools.sys_role.ROLE_ID</code>. 角色表主键
     */
    public SysRoleRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ROLE_ID</code>. 角色表主键
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tools.sys_role.ROLE_CODE</code>. 角色标识
     */
    public SysRoleRecord setRoleCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ROLE_CODE</code>. 角色标识
     */
    public String getRoleCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tools.sys_role.ROLE_NAME</code>. 角色名称
     */
    public SysRoleRecord setRoleName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ROLE_NAME</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.sys_role.ALIVE_FLAG</code>. 生效标志.1:生效;0:删除.
     */
    public SysRoleRecord setAliveFlag(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ALIVE_FLAG</code>. 生效标志.1:生效;0:删除.
     */
    public Integer getAliveFlag() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>tools.sys_role.ADD_USER_ID</code>. 添加用户编号
     */
    public SysRoleRecord setAddUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ADD_USER_ID</code>. 添加用户编号
     */
    public Long getAddUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>tools.sys_role.ADD_TIME</code>. 添加时间
     */
    public SysRoleRecord setAddTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ADD_TIME</code>. 添加时间
     */
    public LocalDateTime getAddTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>tools.sys_role.OPR_USER_ID</code>. 修改用户编号
     */
    public SysRoleRecord setOprUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.OPR_USER_ID</code>. 修改用户编号
     */
    public Long getOprUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>tools.sys_role.OPR_TIME</code>. 修改时间
     */
    public SysRoleRecord setOprTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.OPR_TIME</code>. 修改时间
     */
    public LocalDateTime getOprTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>tools.sys_role.ROLE_TYPE</code>. 角色类型 1管理员 0会员 2：管理员职务相关 3:会员职务相关
     */
    public SysRoleRecord setRoleType(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_role.ROLE_TYPE</code>. 角色类型 1管理员 0会员 2：管理员职务相关 3:会员职务相关
     */
    public Integer getRoleType() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Integer, Long, LocalDateTime, Long, LocalDateTime, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, Integer, Long, LocalDateTime, Long, LocalDateTime, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysRole.SYS_ROLE.ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return SysRole.SYS_ROLE.ROLE_CODE;
    }

    @Override
    public Field<String> field3() {
        return SysRole.SYS_ROLE.ROLE_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return SysRole.SYS_ROLE.ALIVE_FLAG;
    }

    @Override
    public Field<Long> field5() {
        return SysRole.SYS_ROLE.ADD_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SysRole.SYS_ROLE.ADD_TIME;
    }

    @Override
    public Field<Long> field7() {
        return SysRole.SYS_ROLE.OPR_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return SysRole.SYS_ROLE.OPR_TIME;
    }

    @Override
    public Field<Integer> field9() {
        return SysRole.SYS_ROLE.ROLE_TYPE;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public String component2() {
        return getRoleCode();
    }

    @Override
    public String component3() {
        return getRoleName();
    }

    @Override
    public Integer component4() {
        return getAliveFlag();
    }

    @Override
    public Long component5() {
        return getAddUserId();
    }

    @Override
    public LocalDateTime component6() {
        return getAddTime();
    }

    @Override
    public Long component7() {
        return getOprUserId();
    }

    @Override
    public LocalDateTime component8() {
        return getOprTime();
    }

    @Override
    public Integer component9() {
        return getRoleType();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public String value2() {
        return getRoleCode();
    }

    @Override
    public String value3() {
        return getRoleName();
    }

    @Override
    public Integer value4() {
        return getAliveFlag();
    }

    @Override
    public Long value5() {
        return getAddUserId();
    }

    @Override
    public LocalDateTime value6() {
        return getAddTime();
    }

    @Override
    public Long value7() {
        return getOprUserId();
    }

    @Override
    public LocalDateTime value8() {
        return getOprTime();
    }

    @Override
    public Integer value9() {
        return getRoleType();
    }

    @Override
    public SysRoleRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysRoleRecord value2(String value) {
        setRoleCode(value);
        return this;
    }

    @Override
    public SysRoleRecord value3(String value) {
        setRoleName(value);
        return this;
    }

    @Override
    public SysRoleRecord value4(Integer value) {
        setAliveFlag(value);
        return this;
    }

    @Override
    public SysRoleRecord value5(Long value) {
        setAddUserId(value);
        return this;
    }

    @Override
    public SysRoleRecord value6(LocalDateTime value) {
        setAddTime(value);
        return this;
    }

    @Override
    public SysRoleRecord value7(Long value) {
        setOprUserId(value);
        return this;
    }

    @Override
    public SysRoleRecord value8(LocalDateTime value) {
        setOprTime(value);
        return this;
    }

    @Override
    public SysRoleRecord value9(Integer value) {
        setRoleType(value);
        return this;
    }

    @Override
    public SysRoleRecord values(Long value1, String value2, String value3, Integer value4, Long value5, LocalDateTime value6, Long value7, LocalDateTime value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(Long roleId, String roleCode, String roleName, Integer aliveFlag, Long addUserId, LocalDateTime addTime, Long oprUserId, LocalDateTime oprTime, Integer roleType) {
        super(SysRole.SYS_ROLE);

        set(0, roleId);
        set(1, roleCode);
        set(2, roleName);
        set(3, aliveFlag);
        set(4, addUserId);
        set(5, addTime);
        set(6, oprUserId);
        set(7, oprTime);
        set(8, roleType);
    }

    public SysRoleRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysRoleRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setRoleId(json.getLong("ROLE_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ROLE_ID","java.lang.Long",e);
        }
        try {
            setRoleCode(json.getString("ROLE_CODE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ROLE_CODE","java.lang.String",e);
        }
        try {
            setRoleName(json.getString("ROLE_NAME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ROLE_NAME","java.lang.String",e);
        }
        try {
            setAliveFlag(json.getInteger("ALIVE_FLAG"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ALIVE_FLAG","java.lang.Integer",e);
        }
        try {
            setAddUserId(json.getLong("ADD_USER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ADD_USER_ID","java.lang.Long",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ADD_TIME","java.time.LocalDateTime",e);
        }
        try {
            setOprUserId(json.getLong("OPR_USER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPR_USER_ID","java.lang.Long",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column OPR_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("OPR_TIME","java.time.LocalDateTime",e);
        }
        try {
            setRoleType(json.getInteger("ROLE_TYPE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ROLE_TYPE","java.lang.Integer",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ROLE_ID",getRoleId());
        json.put("ROLE_CODE",getRoleCode());
        json.put("ROLE_NAME",getRoleName());
        json.put("ALIVE_FLAG",getAliveFlag());
        json.put("ADD_USER_ID",getAddUserId());
        // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        json.put("OPR_USER_ID",getOprUserId());
        // Omitting unrecognized type java.time.LocalDateTime for column OPR_TIME!
        json.put("ROLE_TYPE",getRoleType());
        return json;
    }

}
