/*
 * This file is generated by jOOQ.
 */
package io.kida.model.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.kida.model.tables.SysUser;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements VertxPojo, Record12<Long, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> {

    private static final long serialVersionUID = -1657409839;

    /**
     * Setter for <code>tools.sys_user.USER_ID</code>. 用户表主键
     */
    public SysUserRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.USER_ID</code>. 用户表主键
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tools.sys_user.USER_ACCOUNT</code>. 登录账号
     */
    public SysUserRecord setUserAccount(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.USER_ACCOUNT</code>. 登录账号
     */
    public String getUserAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tools.sys_user.USER_PASSWORD</code>. 登录密码
     */
    public SysUserRecord setUserPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.USER_PASSWORD</code>. 登录密码
     */
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tools.sys_user.USER_NAME</code>. 用户名称
     */
    public SysUserRecord setUserName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.USER_NAME</code>. 用户名称
     */
    public String getUserName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tools.sys_user.PHONE</code>. 手机
     */
    public SysUserRecord setPhone(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.PHONE</code>. 手机
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tools.sys_user.ADD_TIME</code>. 创建时间
     */
    public SysUserRecord setAddTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.ADD_TIME</code>. 创建时间
     */
    public LocalDateTime getAddTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>tools.sys_user.LOGIN_TIME</code>. 登录时间
     */
    public SysUserRecord setLoginTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.LOGIN_TIME</code>. 登录时间
     */
    public LocalDateTime getLoginTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>tools.sys_user.LOGIN_IP</code>. 登录IP
     */
    public SysUserRecord setLoginIp(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.LOGIN_IP</code>. 登录IP
     */
    public String getLoginIp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tools.sys_user.STATUS</code>. 状态.1:启用,0:禁用,-1:删除
     */
    public SysUserRecord setStatus(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.STATUS</code>. 状态.1:启用,0:禁用,-1:删除
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>tools.sys_user.WX_ID</code>. 绑定微信id
     */
    public SysUserRecord setWxId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.WX_ID</code>. 绑定微信id
     */
    public String getWxId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>tools.sys_user.IMG_URL</code>. 图片url地址
     */
    public SysUserRecord setImgUrl(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.IMG_URL</code>. 图片url地址
     */
    public String getImgUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>tools.sys_user.MAIL</code>.
     */
    public SysUserRecord setMail(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>tools.sys_user.MAIL</code>.
     */
    public String getMail() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysUser.SYS_USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return SysUser.SYS_USER.USER_ACCOUNT;
    }

    @Override
    public Field<String> field3() {
        return SysUser.SYS_USER.USER_PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return SysUser.SYS_USER.USER_NAME;
    }

    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.PHONE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SysUser.SYS_USER.ADD_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SysUser.SYS_USER.LOGIN_TIME;
    }

    @Override
    public Field<String> field8() {
        return SysUser.SYS_USER.LOGIN_IP;
    }

    @Override
    public Field<Integer> field9() {
        return SysUser.SYS_USER.STATUS;
    }

    @Override
    public Field<String> field10() {
        return SysUser.SYS_USER.WX_ID;
    }

    @Override
    public Field<String> field11() {
        return SysUser.SYS_USER.IMG_URL;
    }

    @Override
    public Field<String> field12() {
        return SysUser.SYS_USER.MAIL;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserAccount();
    }

    @Override
    public String component3() {
        return getUserPassword();
    }

    @Override
    public String component4() {
        return getUserName();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public LocalDateTime component6() {
        return getAddTime();
    }

    @Override
    public LocalDateTime component7() {
        return getLoginTime();
    }

    @Override
    public String component8() {
        return getLoginIp();
    }

    @Override
    public Integer component9() {
        return getStatus();
    }

    @Override
    public String component10() {
        return getWxId();
    }

    @Override
    public String component11() {
        return getImgUrl();
    }

    @Override
    public String component12() {
        return getMail();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserAccount();
    }

    @Override
    public String value3() {
        return getUserPassword();
    }

    @Override
    public String value4() {
        return getUserName();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public LocalDateTime value6() {
        return getAddTime();
    }

    @Override
    public LocalDateTime value7() {
        return getLoginTime();
    }

    @Override
    public String value8() {
        return getLoginIp();
    }

    @Override
    public Integer value9() {
        return getStatus();
    }

    @Override
    public String value10() {
        return getWxId();
    }

    @Override
    public String value11() {
        return getImgUrl();
    }

    @Override
    public String value12() {
        return getMail();
    }

    @Override
    public SysUserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysUserRecord value2(String value) {
        setUserAccount(value);
        return this;
    }

    @Override
    public SysUserRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    @Override
    public SysUserRecord value4(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public SysUserRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public SysUserRecord value6(LocalDateTime value) {
        setAddTime(value);
        return this;
    }

    @Override
    public SysUserRecord value7(LocalDateTime value) {
        setLoginTime(value);
        return this;
    }

    @Override
    public SysUserRecord value8(String value) {
        setLoginIp(value);
        return this;
    }

    @Override
    public SysUserRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysUserRecord value10(String value) {
        setWxId(value);
        return this;
    }

    @Override
    public SysUserRecord value11(String value) {
        setImgUrl(value);
        return this;
    }

    @Override
    public SysUserRecord value12(String value) {
        setMail(value);
        return this;
    }

    @Override
    public SysUserRecord values(Long value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, String value8, Integer value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(Long userId, String userAccount, String userPassword, String userName, String phone, LocalDateTime addTime, LocalDateTime loginTime, String loginIp, Integer status, String wxId, String imgUrl, String mail) {
        super(SysUser.SYS_USER);

        set(0, userId);
        set(1, userAccount);
        set(2, userPassword);
        set(3, userName);
        set(4, phone);
        set(5, addTime);
        set(6, loginTime);
        set(7, loginIp);
        set(8, status);
        set(9, wxId);
        set(10, imgUrl);
        set(11, mail);
    }

    public SysUserRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public SysUserRecord fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setUserId(json.getLong("USER_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_ID","java.lang.Long",e);
        }
        try {
            setUserAccount(json.getString("USER_ACCOUNT"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_ACCOUNT","java.lang.String",e);
        }
        try {
            setUserPassword(json.getString("USER_PASSWORD"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_PASSWORD","java.lang.String",e);
        }
        try {
            setUserName(json.getString("USER_NAME"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("USER_NAME","java.lang.String",e);
        }
        try {
            setPhone(json.getString("PHONE"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("PHONE","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ADD_TIME","java.time.LocalDateTime",e);
        }
        try {
            // Omitting unrecognized type java.time.LocalDateTime for column LOGIN_TIME!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("LOGIN_TIME","java.time.LocalDateTime",e);
        }
        try {
            setLoginIp(json.getString("LOGIN_IP"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("LOGIN_IP","java.lang.String",e);
        }
        try {
            setStatus(json.getInteger("STATUS"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("STATUS","java.lang.Integer",e);
        }
        try {
            setWxId(json.getString("WX_ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("WX_ID","java.lang.String",e);
        }
        try {
            setImgUrl(json.getString("IMG_URL"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("IMG_URL","java.lang.String",e);
        }
        try {
            setMail(json.getString("MAIL"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("MAIL","java.lang.String",e);
        }
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("USER_ID",getUserId());
        json.put("USER_ACCOUNT",getUserAccount());
        json.put("USER_PASSWORD",getUserPassword());
        json.put("USER_NAME",getUserName());
        json.put("PHONE",getPhone());
        // Omitting unrecognized type java.time.LocalDateTime for column ADD_TIME!
        // Omitting unrecognized type java.time.LocalDateTime for column LOGIN_TIME!
        json.put("LOGIN_IP",getLoginIp());
        json.put("STATUS",getStatus());
        json.put("WX_ID",getWxId());
        json.put("IMG_URL",getImgUrl());
        json.put("MAIL",getMail());
        return json;
    }

}
